### ISSUE TITLE
request for getSex for  list of pedigrees and singletons 

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#15]
It would be nice with a version of getSex working
for  a list of pedigrees and singletons:

``` r
library(pedtools)
v = list(singleton(1),singleton(2))
getSex(v,"1")
#> Error: Input is not a `ped` object
```

<sup>Created on 2018-12-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by magnusdv** [comment]
This is implemented now, with `getSex()` allowing `x` to be a list of ped objects:

``` r
library(pedtools)
v = list(singleton(id = "a", sex = 2), singleton(id = 1, sex = 1))
getSex(v, c("a", 1))
#> [1] 2 1
```

<sup>Created on 2018-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
