### ISSUE TITLE
Duplicated individuals

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#2]
Apparenty `nuclearPed` and `likelihood`(https://github.com/magnusdv/pedprobr) tolerate some duplication, not `plot` :
``` r
library(pedtools)
library(pedprobr)
x = nuclearPed(children = c("sib1", "sib1"))
m = marker(x, sib1 = 1:2, sib1 = 1, alleles = 1:2)
likelihood(x,m)
#> [1] 0.25
plot(x,m)
#> Error in kinship2::pedigree(id = ped$id, dadid = ped$fid, momid = ped$mid, : Duplicate subject id: sib1
```

Created on 2018-08-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by magnusdv** [comment]
Good catch, duplicated id's should definitely raise an error during pedigree construction. 

Plot labels _can_ be duplicated, of course, when they are given explicitly in the `plot()` call using the `id.labels` argument. (For instance, it is often useful to use empty labels for many pedigree members.)

**Comment by magnusdv** [comment]
On a side note, this reminds me of something I've swept under the rug so far: The class of pedigrees allowed in `pedtools` is larger than for the `kinship2` package (which does the plotting). Hence certain pedigrees (e.g. pedigrees involving selfing) cannot be plotted as of yet.

**Comment by magnusdv** [comment]
With 44598d5 duplicated IDs are caught in `relabel()`, resolving the original error here.
