### ISSUE TITLE
Problem installing with `build_vignettes = TRUE`

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#22]
Installation failed just now iff I asked for the vignette:

devtools::install_github("magnusdv/pedtools", 
                         build_vignettes = TRUE, force = TRUE)
#> Downloading GitHub repo magnusdv/pedtools@master
#> 
#>   
  
  
   checking for file 'C:\Users\theg\AppData\Local\Temp\RtmpkVIyn5\remotes2fe447ce73ab\magnusdv-pedtools-93add0e/DESCRIPTION' ...
  
v  checking for file 'C:\Users\theg\AppData\Local\Temp\RtmpkVIyn5\remotes2fe447ce73ab\magnusdv-pedtools-93add0e/DESCRIPTION'
#> 
  
  
  
-  preparing 'pedtools':
#>    checking DESCRIPTION meta-information ...
  
   checking DESCRIPTION meta-information ... 
  
v  checking DESCRIPTION meta-information
#> 
  
  
  
-  installing the package to build vignettes
#> 
  
  
  
   creating vignettes ...
  
   creating vignettes ... 
  
E  creating vignettes (8.4s)
#>    pandoc.exe: <<loop>>
#>    Error: processing vignette 'pedtools.Rmd' failed with diagnostics:
#>    pandoc document conversion failed with error 1
#>    Execution halted
#> 
#> Error: Failed to install 'pedtools' from GitHub:
#>   System command error, exit status: 1, stdout + stderr:
#> E> * checking for file 'C:\Users\theg\AppData\Local\Temp\RtmpkVIyn5\remotes2fe447ce73ab\magnusdv-pedtools-93add0e/DESCRIPTION' ... OK
#> E> * preparing 'pedtools':
#> E> * checking DESCRIPTION meta-information ... OK
#> E> * installing the package to build vignettes
#> E> * creating vignettes ... ERROR
#> E> pandoc.exe: <<loop>>
#> E> Error: processing vignette 'pedtools.Rmd' failed with diagnostics:
#> E> pandoc document conversion failed with error 1
#> E> Execution halted
Created on 2019-08-11 by the reprex package (v0.3.0)

**Comment by magnusdv** [comment]
Wild guess: Do you have the package `kableExtra` installed? 
If not, could you install it and try again?

**Comment by thoree** [comment]
Thanks - fine with `kableExtra`.
