### ISSUE TITLE
Feature requests for  `transferMarkers`

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#26]
We discussed some potential new features of the very useful function `transferMarkers`:
(i) add optional checking for sex consistency and (ii) optionally return first argument `from` with transferred
genotypes removed.

**Comment by magnusdv** [comment]
Thanks. Optional sex check is implemented as of 27ab08f.

Regarding the other feature I'm not too keen, as it would change the output structure. I suggest doing this with `setAlleles()`.
