### ISSUE TITLE
Check for duplicated allele names?

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#28]
``` r
library(pedprobr)
#> Loading required package: pedtools
x = nuclearPed()
m1 = marker(x,"1" = "a/a",   afreq = c(a = 0.9, a = 0.1))
likelihood(x,m1)
#> [1] 0.81
```

<sup>Created on 2020-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by magnusdv** [comment]
Duplicated allele labels are now caught in marker creation:

``` r
library(pedtools)

x = singleton(1)
marker(x, afreq = c(a = 0.1, a = 0.9))
#> Error: Duplicated allele label: a
```

<sup>Created on 2020-08-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
