### ISSUE TITLE
New errors breaking (marriage) loops

### ISSUE THREAD

**Issue by zachariae** [magnusdv/pedtools#37]
Currently, I am facing a new error when trying to break loops:
If the pedigree has marriage loops, I got the error: 

Marriage loops detected, trying different selection method
Loop breakers: 001, 004 
Error: Cannot restore to `ped` object: Disconnected input. 

Breaking marriage loops worked for me the last time I used the package. At least I got an error message, when in a pedigree with 2 marriage loops, breaking them was not possible.

Furthermore, if the pedigree is split, and has _comp elements, I got the error-message "WARNING:numerical expression has 2 elements: only the first used". I am not sure, how this worked the last time, 

Best wishes, Silke

**Comment by magnusdv** [comment]
Hi, thanks for reporting the issue. 

Could you please provide a reproducible example? (I strongly recommend the [reprex](https://reprex.tidyverse.org/) package.)

Also, it might be helpful for me to know what sort of analysis you want to do. Many of the high-level functions in the ped suite do the necessary loop breaking internally.

**Comment by zachariae** [comment]
My analysis is a co-segregation analysis, which seems not to break the loops because I get an error for some files with loops.

**Comment by magnusdv** [comment]
I see. If you could provide an example I'd be happy to look into it.

**Comment by magnusdv** [comment]
Closing this now, but feel free to reopen if needed.
