### ISSUE TITLE
fill argument for `plot.ped()`

### ISSUE THREAD

**Issue by chrcarrizosa** [magnusdv/pedtools#39]

**Comment by magnusdv** [comment]
This is implemented now, as of 5348064:

``` r
library(pedtools)
x = nuclearPed(1)

# Fill colors
plot(x, fill = 2:4)
```

![](https://i.imgur.com/LKNNFaQ.png)

``` r
# Specify individual filling
plot(x, fill = c(`3` = 2))
```

![](https://i.imgur.com/BgFPn9V.png)

``` r
# Or group-wise
plot(x, fill = list(blue = founders))
```

![](https://i.imgur.com/NJe61ZW.png)

``` r
# Colored outline and fill
plot(x, fill = 2:4, col = 1:3, lwd = 3)
```

![](https://i.imgur.com/REdoptz.png)

``` r
# Linetype
plot(x, lty = c(`3` = "dashed"), symbolsize = 1.5)
```

![](https://i.imgur.com/LtLZA5x.png)

<sup>Created on 2023-04-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
