### ISSUE TITLE
posCm

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#5]
Here is something I don't understand:

``` r
library(pedtools)
x = nuclearPed(1)
m = marker(x)
chrom(m) = 1 # OK, but
posCm(m) = 100
#> Error in posCm(m) = 100: could not find function "posCm<-"
```

Created on 2018-08-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by magnusdv** [comment]
Ah, yes - the setter functions for `posCm`,  `posMb` and `mutmat` are not in place yet. So for now you'll have to stick with setting these during construction: `marker(x, posCm = 100)`.

I'll get to these eventually; I'll let this issue stay open as a reminder.
