### ISSUE TITLE
`ped` function speedup

### ISSUE THREAD

**Issue by deepchocolate** [magnusdv/pedtools#54]
I'm running the `ped` function on a quite large sample which takes ages...
I've experimented a bit and it seems that this part eats up quite much time:
https://github.com/magnusdv/pedtools/blob/fa784e1f065e7a40e455169a2354d083da97af37/R/ped_connected.R#L50-L55

Maybe this can be done with `sapply` instead to avoid using the for-loop?
```
sapply(founders, function (x) {
    if (env$comp[x] == 0) {
      tag = tag + 1
      DFS(x, tag)
    }
  });
```
Seems to cut time by half when I modified this and tested on 20K trios.

**Comment by magnusdv** [comment]
Hi, nice to see a bit of 'stress testing' of **pedtools**. :)

The `ped()` and `connectedComponents()` functions weren't really designed with that kind of scale in mind, so I'm not too surprised that 20k components gives it a mouthful.

I appreciate your proposed change. but I'm not sure this is the way to go. I don't think it gives the same output as the original code. In any case, using `sapply` just for side effects without using the output feels quite strange to me. 

However, if you know beforehand that your data consists of trios, perhaps you could assign the family IDs yourself and use `as.ped()`? That should be quite a lot faster. For example:

``` r
library(pedtools)

N = 10 # 20000
trios = lapply(1:N, function(i) nuclearPed() |> relabel((1:3) + 10*i))
df = do.call(rbind, lapply(trios, as.data.frame))

# Supply family ID
df$famid = rep(paste0("F", 1:N), each = 3)
head(df)
#>   id fid mid sex famid
#> 1 11   0   0   1    F1
#> 2 12   0   0   2    F1
#> 3 13  11  12   1    F1
#> 4 21   0   0   1    F2
#> 5 22   0   0   2    F2
#> 6 23  21  22   1    F2

# Convert to ped
x = as.ped(df)

head(x, 2)
#> $F1
#>  id fid mid sex
#>  11   *   *   1
#>  12   *   *   2
#>  13  11  12   1
#> 
#> $F2
#>  id fid mid sex
#>  21   *   *   1
#>  22   *   *   2
#>  23  21  22   1
```

<sup>Created on 2024-09-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by deepchocolate** [comment]
The thing is that the for-loop does not store anything besides the value of `tag = tag + 1` which is passed to `DFO(fou, tag)`. `DFO` assigns value to `env$comp` which is defined outside the scope of the for-loop.
https://github.com/magnusdv/pedtools/blob/fa784e1f065e7a40e455169a2354d083da97af37/R/ped_connected.R#L36-L46

Thank you for the above suggestion, I wasn't aware of how one could use `as.ped`. I will try it out! 

I understand that they way I use pedtools is not the main target, but to make a long story short, this package was the only one I got working given computational environment, memory limitations, reproducibility etc.

**Comment by magnusdv** [comment]
Ok great, good luck. I'm closing this now, but feel free to reopen.
