### ISSUE TITLE
plotPedList not run example

### ISSUE THREAD

**Issue by thoree** [magnusdv/pedtools#7]
The 'not run' example of plotPedList reads
...
plotPedList(list(plot1, plot2, plot3, plot4), widths=c(2,3,1,2),
            frames=list(1,2:3,4), available=T, newdev=T)
....
I f available=TRUE is removed, the example runs nicely  without warnings.

**Comment by magnusdv** [comment]
Ah, thanks. The `available` option is a relic from paramlink. I've updated these examples now.
